[options]
admin_passwd = admin
http_port = 8002
db_host = 127.0.0.1
db_port = 5432
db_user = zahed
db_password = 
addons_path = odoo/addons
db_name = raptronOdoo
dbfilter = ^raptronOdoo$
list_db = True
data_dir = /Users/zahed/.local/share/Odoo
